---
name: PR Lint

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  Linter:
    name: PR Lint
    runs-on: ubuntu-latest
    steps:
      - uses: ivuorinen/actions/pr-lint@main
