---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions:
  contents: write
  statuses: write

jobs:
  Draft:
    uses: ivuorinen/.github/.github/workflows/sync-labels.yml@main
